# Generated by Django 4.0.5 on 2022-07-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defects', '0001_initial'),
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('ata_chapter', models.CharField(max_length=20)),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_card', to='defects.defect')),
                ('plane_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msgs.planetype')),
            ],
            options={
                'db_table': 'task_card',
            },
        ),
        migrations.CreateModel(
            name='TaskCardStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('task_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='task_cards.taskcard')),
            ],
            options={
                'db_table': 'task_card_step',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=10)),
                ('task_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='task_cards.taskcard')),
            ],
            options={
                'db_table': 'task_card_material',
            },
        ),
    ]
