# Generated by Django 4.0.5 on 2022-07-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcardstep',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
