# Generated by Django 4.0.5 on 2022-07-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_cards', '0002_alter_taskcardstep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcardstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
