# Generated by Django 4.0.5 on 2022-07-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_cards', '0003_alter_taskcardstep_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='TaskCardMaterial',
        ),
        migrations.AlterModelOptions(
            name='taskcardstep',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='taskcard',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='ata_chapter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='taskcardstep',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcardstep',
            name='text',
            field=models.TextField(default='-----'),
        ),
    ]
