# Generated by Django 4.0.5 on 2022-07-25 19:47

from django.db import migrations, models
import django.db.models.deletion
import task_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_cards', '0004_rename_materials_taskcardmaterial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'staff_category',
            },
        ),
        migrations.AddField(
            model_name='taskcardstep',
            name='manhours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='ata_chapter',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[task_cards.models.latex_sym_validator]),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='description',
            field=models.CharField(max_length=255, validators=[task_cards.models.latex_sym_validator]),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='number',
            field=models.CharField(max_length=30, validators=[task_cards.models.latex_sym_validator]),
        ),
        migrations.AlterField(
            model_name='taskcardmaterial',
            name='description',
            field=models.CharField(max_length=50, validators=[task_cards.models.latex_sym_validator]),
        ),
        migrations.AlterField(
            model_name='taskcardmaterial',
            name='part_number',
            field=models.CharField(max_length=30, validators=[task_cards.models.latex_sym_validator]),
        ),
        migrations.AlterField(
            model_name='taskcardmaterial',
            name='qty',
            field=models.CharField(max_length=10, validators=[task_cards.models.latex_sym_validator]),
        ),
        migrations.AlterField(
            model_name='taskcardstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/%H/%M'),
        ),
        migrations.AlterField(
            model_name='taskcardstep',
            name='text',
            field=models.TextField(default='-----', validators=[task_cards.models.latex_sym_validator]),
        ),
        migrations.AddField(
            model_name='taskcardstep',
            name='staff_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_cards.staffcategory'),
        ),
    ]
