# Generated by Django 4.0.5 on 2022-07-25 20:39

from django.db import migrations, models
import task_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_cards', '0005_staffcategory_taskcardstep_manhours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcardstep',
            name='manhours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='taskcardstep',
            name='text',
            field=models.TextField(default='', validators=[task_cards.models.latex_sym_validator]),
        ),
    ]
