# Generated by Django 4.0.5 on 2022-06-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagedescription',
            old_name='plane_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='plane',
            old_name='plane_type',
            new_name='type',
        ),
    ]
