# Generated by Django 4.0.5 on 2022-06-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='airline_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
