# Generated by Django 4.0.5 on 2022-06-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_plane_airline_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultreport',
            name='plane',
        ),
        migrations.AlterField(
            model_name='mmsg',
            name='defect_status',
            field=models.CharField(blank=True, default='Not open', max_length=10, null=True),
        ),
    ]
