# Generated by Django 4.0.5 on 2022-06-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_rename_plane_type_messagedescription_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagedescription',
            old_name='type',
            new_name='plane_type',
        ),
        migrations.RenameField(
            model_name='plane',
            old_name='type',
            new_name='plane_type',
        ),
    ]
