# Generated by Django 4.0.5 on 2022-06-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0003_remove_faultreport_plane_alter_mmsg_defect_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acarsmsgraw',
            name='airplane',
        ),
    ]
