# Generated by Django 4.0.5 on 2022-06-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0003_rename_type_messagedescription_plane_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plane',
            old_name='plane_type',
            new_name='type',
        ),
    ]
