# Generated by Django 4.0.5 on 2022-06-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0004_rename_plane_type_plane_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedescription',
            name='some_test_field',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
