# Generated by Django 4.0.5 on 2022-07-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0004_remove_acarsmsgraw_airplane'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mmsg',
            options={'ordering': ['-msg_date_time']},
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('NOT_OPEN', 'NOT_OPEN'), ('PENDING', 'PENDING')], default='NOT_OPEN', max_length=12)),
                ('mmsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect', to='msgs.mmsg')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='msgs.plane')),
            ],
        ),
    ]
