# Generated by Django 4.0.5 on 2022-07-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0005_alter_mmsg_options_defect'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='defect',
            table='defect',
        ),
    ]
