# Generated by Django 4.0.5 on 2022-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0006_remove_messagedescription_some_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmsg',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
