# Generated by Django 4.0.5 on 2022-07-01 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0006_alter_defect_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'defect_status',
            },
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='msgs.defectstatus'),
        ),
    ]
