# Generated by Django 4.0.5 on 2022-06-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0007_mmsg_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(blank=True, max_length=3, null=True)),
                ('fde_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'fde',
            },
        ),
        migrations.CreateModel(
            name='FdeMmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fde', to='msgs.fde')),
            ],
            options={
                'db_table': 'fde_mmsg',
            },
        ),
        migrations.RemoveField(
            model_name='mmsg',
            name='plf',
        ),
        migrations.AlterField(
            model_name='messagedescription',
            name='plane_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_descriptions', to='msgs.planetype'),
        ),
        migrations.DeleteModel(
            name='FdeMsg',
        ),
        migrations.AddField(
            model_name='fdemmsg',
            name='mmsg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmsg', to='msgs.mmsg'),
        ),
        migrations.AddField(
            model_name='fdemmsg',
            name='plf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plf', to='msgs.faultreport'),
        ),
    ]
