# Generated by Django 4.0.5 on 2022-07-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0008_remove_defect_mmsg_mmsg_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='plane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='msgs.plane'),
        ),
    ]
