# Generated by Django 4.0.5 on 2022-07-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0009_alter_defect_plane'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('after_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_history', to='msgs.defectstatus')),
                ('before_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_history', to='msgs.defectstatus')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='msgs.defect')),
            ],
            options={
                'db_table': 'defect_history',
            },
        ),
    ]
