# Generated by Django 4.0.5 on 2022-07-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0011_alter_messagedescription_fim_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmsg',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maint_message', to='msgs.messagedescription'),
        ),
    ]
