# Generated by Django 4.0.5 on 2022-07-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0012_mmsg_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
